CREATE TABLE PAYMENTS
(
  ID INT NOT NULL,
  Method INT NOT NULL,
  Amount INT NOT NULL,
  Value INT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CUSTOMERS
(
  Id INT NOT NULL,
  Name INT NOT NULL,
  Address INT NOT NULL,
  Contact INT NOT NULL,
  History_orders INT NOT NULL,
  ID INT NOT NULL,
  PRIMARY KEY (Id),
  FOREIGN KEY (ID) REFERENCES PAYMENTS(ID)
);

CREATE TABLE PRODUCT
(
  Id INT NOT NULL,
  Name INT NOT NULL,
  Price INT NOT NULL,
  Quantity INT NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE ORDER_INFO
(
  Price INT NOT NULL,
  id_order INT NOT NULL,
  Discount INT NOT NULL,
  Quantity INT NOT NULL,
  Id INT NOT NULL,
  PRIMARY KEY (id_order),
  FOREIGN KEY (Id) REFERENCES PRODUCT(Id)
);

CREATE TABLE ORDERS
(
  Id INT NOT NULL,
  Customer_id INT NOT NULL,
  Time INT NOT NULL,
  id_order INT NOT NULL,
  PRIMARY KEY (Id),
  FOREIGN KEY (id_order) REFERENCES ORDER_INFO(id_order)
);

CREATE TABLE STORE
(
  Id INT NOT NULL,
  Address INT NOT NULL,
  Name INT NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE MAKE
(
  Id INT NOT NULL,
  Id INT NOT NULL,
  PRIMARY KEY (Id, Id),
  FOREIGN KEY (Id) REFERENCES ORDERS(Id),
  FOREIGN KEY (Id) REFERENCES CUSTOMERS(Id)
);

CREATE TABLE FROM_ORDER
(
  Id INT NOT NULL,
  Id INT NOT NULL,
  PRIMARY KEY (Id, Id),
  FOREIGN KEY (Id) REFERENCES ORDERS(Id),
  FOREIGN KEY (Id) REFERENCES STORE(Id)
);

CREATE TABLE HAS
(
  Id INT NOT NULL,
  Id INT NOT NULL,
  PRIMARY KEY (Id, Id),
  FOREIGN KEY (Id) REFERENCES STORE(Id),
  FOREIGN KEY (Id) REFERENCES PRODUCT(Id)
);